# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch except master, ignore all version tags
  push:
    branches:
      - "**"
      - "!master"
    tags-ignore:
      - "v**"
  # Triggers the workflow on PRs to master branch
  pull_request:
    branches:
      - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - uses: actions/setup-node@v2
        with:
          node-version: "8.x"
          registry-url: "https://registry.npmjs.org"

      - shell: pwsh
        name: Install NPM dependencies
        run: npm install

      - shell: pwsh
        name: Set package version
        id: set-version
        run: |
          $gitVersion = ((git describe --abbrev=0 --match v*.* --tags) -replace "(v\d+.\d+.\d+).*", '$1') 
          $version = "$gitVersion-build-${{github.run_id}}"
          npm version "$version" --no-git-tag-version --force
          echo "VERSION::${version}" >> $GITHUB_ENV

      - shell: pwsh
        name: Pack the package
        run: npm pack --loglevel=error

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generator-sitecore-engx-scaffold.tgz
          path: |
            generator-sitecore-engx-scaffold-*.tgz
